

###Server Variables###
@SERVER=http://localhost:7000


@ID=65674352fab157b61b2e8df0

### Test Server###

GET {{SERVER}}

####Register user ####

POST {{SERVER}}/api/register
content-type: application/json

{
    "email": "Edson@s.com",
    "password": "12345678",
    "name": "edson "
}

###LOGIN####

POST {{SERVER}}/api/login
content-type: application/json

{
  
   "password": "12345678",
    "email": "Edson@s.com"
  
}

###Create/add an Item to a to-do-list###


POST {{SERVER}}/api/create
content-type: application/json

{
     "name": "Bread",
      "description": "The childrens lunch box"
}


###READ###

GET {{SERVER}}/api/items


###Update###

PUT {{SERVER}}/api/items/65674352fab157b61b2e8df0
content-type: application/json

{

    "name": "apple", 
    "description": "We need butter for lunch box"
}






    






