

###Server Variables###
@SERVER=http://localhost:7000

### Test Server

GET {{SERVER}}

####Register user ####

POST {{SERVER}}/api/register
content-type: application/json

{
    "email": "Edson@s.com",
    "password": "12345678",
    "name": "edson "
}

###LOGIN####

POST {{SERVER}}/api/login
content-type: application/json

{
  
   "password": "12345678",
    "email": "Edson@s.com"
  
}






    






