

###Server Variables###
@SERVER=http://localhost:7000

### Test Server

GET {{SERVER}}

####Register user ####

POST {{SERVER}}/api/register
content-type: application/json

{
    "email": "kwazi@ss.com",
    "password": "123456",
    "name": "Kwazi "
}

####Login####


    






